version: "3.3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  rest-api:
    build: ./src/rest-api
    hostname: rest-api
    env_file: ./src/rest-api/.env
    ports:
      - 4000:7000
    links:
      - mongo