#!/bin/bash

clear

echo "Stopping mongo Docker containers"
docker stop mongodb-test
echo "Cleaning up docker containers"
docker rm -f mongodb-test
echo "Starting mongodb" && \
docker run -d -p 27030:27017 --name mongodb-test mongo
echo "mongodb started!"